# Generated by Django 3.1.6 on 2021-03-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20210305_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='producent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.producent'),
        ),
    ]
