# Generated by Django 3.1.6 on 2022-08-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20210412_2226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
